(()=>{'use strict';
const API='https://xnlkjkrkkehplsbbziil.supabase.co/functions/v1/arlab-player-checkin-api';
const LABELS={1:'Muy, muy ligero',2:'Muy ligero',3:'Ligero',4:'Algo pesado',5:'Pesado',6:'Más pesado',7:'Muy pesado',8:'Muy, muy pesado',9:'Máximo',10:'Extremo'};
let fieldRpe=0,gymRpe=0;
const nativeFetch=window.fetch.bind(window);
const style=document.createElement('style');style.textContent=`
.v710-rpe-scale{display:grid;grid-template-columns:repeat(10,minmax(60px,1fr));gap:8px;margin-top:12px}.v710-rpe-btn{border:1px solid #d8e4f1;border-radius:12px;background:#fff;color:#17324f;padding:10px 5px;min-height:78px;cursor:pointer;text-align:center;transition:.15s}.v710-rpe-btn:hover{border-color:#89b8ff;transform:translateY(-1px)}.v710-rpe-btn.selected{border:2px solid #1769e8;background:#eef5ff;box-shadow:0 0 0 3px #1769e812}.v710-rpe-num{display:block;font-size:22px;font-weight:950;color:#1769e8}.v710-rpe-label{display:block;font-size:9px;line-height:1.15;color:#688099;margin-top:5px;font-weight:800}.v710-rpe-note{font-size:12px;color:#71849d;margin-top:5px}.v710-checkout-badge{display:inline-flex;align-items:center;padding:5px 8px;border-radius:999px;background:#eaf3ff;color:#1769e8;font-size:10px;font-weight:900;margin-left:6px}@media(max-width:850px){.v710-rpe-scale{grid-template-columns:repeat(5,1fr)}}@media(max-width:520px){.v710-rpe-scale{grid-template-columns:repeat(2,1fr);gap:8px}.v710-rpe-btn{min-height:65px;padding:8px}.v710-rpe-label{font-size:10px}}
`;document.head.appendChild(style);
function token(){return localStorage.getItem('arlabPlayerToken')||''}
function htmlScale(kind,value){return `<div class="v710-rpe-scale" data-v710-scale="${kind}">${Array.from({length:10},(_,i)=>i+1).map(n=>`<button type="button" class="v710-rpe-btn ${n===value?'selected':''}" data-v710-kind="${kind}" data-v710-value="${n}"><span class="v710-rpe-num">${n}</span><span class="v710-rpe-label">${LABELS[n]}</span></button>`).join('')}</div>`}
function ensureLegacyMarker(shell){let x=shell.querySelector('[data-v710-legacy-marker]');if(fieldRpe&&gymRpe){if(!x){x=document.createElement('span');x.hidden=true;x.dataset.v710LegacyMarker='1';x.dataset.choiceName='coRpe';x.dataset.choice='maximum';x.className='selected';shell.appendChild(x)}}else if(x)x.remove()}
function select(kind,n,shell){if(kind==='field')fieldRpe=n;else gymRpe=n;shell.querySelectorAll(`[data-v710-kind="${kind}"]`).forEach(b=>b.classList.toggle('selected',Number(b.dataset.v710Value)===n));ensureLegacyMarker(shell)}
async function preload(shell){try{const r=await nativeFetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token()},body:JSON.stringify({action:'me'})});if(!r.ok)return;const j=await r.json(),e=j.checkOut||{};const f=Number(e.fieldRpe||e.fieldRpeScore)||0,g=Number(e.gymRpe||e.gymRpeScore)||0;if(f>=1&&f<=10)fieldRpe=f;if(g>=1&&g<=10)gymRpe=g;shell.querySelectorAll('[data-v710-scale="field"]').forEach(x=>x.outerHTML=htmlScale('field',fieldRpe));shell.querySelectorAll('[data-v710-scale="gym"]').forEach(x=>x.outerHTML=htmlScale('gym',gymRpe));bindButtons(shell);ensureLegacyMarker(shell)}catch{}}
function bindButtons(shell){shell.querySelectorAll('[data-v710-value]').forEach(b=>b.onclick=()=>select(b.dataset.v710Kind,Number(b.dataset.v710Value),shell))}
function patchChoiceCard(){document.querySelectorAll('.modeCard[data-mode="checkout"] p').forEach(p=>p.textContent='Después del entrenamiento: dureza de campo y gimnasio (1–10), comentario y puntos exactos sensibles.')}
function mount(){patchChoiceCard();const save=document.getElementById('saveCheckOut');if(!save)return;const shell=save.closest('.formShell');if(!shell||shell.dataset.v710Checkout==='1')return;shell.dataset.v710Checkout='1';fieldRpe=0;gymRpe=0;const steps=shell.querySelector('.steps');if(!steps)return;const old=[...steps.children].filter(x=>x.classList.contains('step'));if(old.length<3)return;
const s1=document.createElement('div');s1.className='step v710CheckoutStep';s1.innerHTML=`<div class="stepNum">1</div><div><h3>¿Cómo de duro ha sido el entrenamiento de hoy en campo?<span class="v710-checkout-badge">1–10</span></h3><p class="v710-rpe-note">1 muy, muy ligero · 10 extremo</p>${htmlScale('field',fieldRpe)}</div>`;
const s2=document.createElement('div');s2.className='step v710CheckoutStep';s2.innerHTML=`<div class="stepNum">2</div><div><h3>¿Cómo de duro ha sido el entrenamiento de hoy en gimnasio?<span class="v710-checkout-badge">1–10</span></h3><p class="v710-rpe-note">1 muy, muy ligero · 10 extremo</p>${htmlScale('gym',gymRpe)}</div>`;
old[0].replaceWith(s1,s2);const n2=old[1].querySelector('.stepNum');if(n2)n2.textContent='3';const n3=old[2].querySelector('.stepNum');if(n3)n3.textContent='4';bindButtons(shell);ensureLegacyMarker(shell);preload(shell)}
window.fetch=async function(input,init={}){try{const u=typeof input==='string'?input:(input&&input.url)||'';const method=String(init.method||(input&&input.method)||'GET').toUpperCase();if(method==='POST'&&u.includes('/arlab-player-checkin-api')&&typeof init.body==='string'){const j=JSON.parse(init.body);if(j&&j.action==='submit_checkout'){if(!(fieldRpe>=1&&fieldRpe<=10&&gymRpe>=1&&gymRpe<=10)){return new Response(JSON.stringify({error:'Selecciona la dureza de campo y de gimnasio (1–10)'}),{status:400,headers:{'content-type':'application/json'}})}j.payload={...(j.payload||{}),fieldRpe,gymRpe};return nativeFetch(input,{...init,body:JSON.stringify(j)})}}}catch{}return nativeFetch(input,init)};
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
