(()=>{'use strict';
const API='https://xnlkjkrkkehplsbbziil.supabase.co/functions/v1/arlab-player-checkin-api';
const ASSET='https://xnlkjkrkkehplsbbziil.supabase.co/storage/v1/object/public/arlab-v699-static/';
const $=s=>document.querySelector(s);
let token=localStorage.getItem('arlabPlayerToken')||'',state=null,mode='',checkInPoints=[],checkOutPoints=[];
const FEEL=[['very_bad','Muy mal','1/6','☹'],['bad','Mal','2/6','☹'],['regular','Regular','3/6','😐'],['good','Bien','4/6','🙂'],['very_good','Muy bien','5/6','🙂'],['excellent','Excelente','6/6','🙂']];
const READY=[['very_weak','Muy débil','1/6','☹'],['weak','Débil','2/6','☹'],['medium','Medio','3/6','😐'],['good','Bien','4/6','🙂'],['very_good','Muy bien','5/6','🙂'],['excellent','Excelente','6/6','🙂']];
const RPE=[['very_light','Muy suave','1/6','🙂'],['light','Suave','2/6','🙂'],['moderate','Moderado','3/6','😐'],['hard','Duro','4/6','😐'],['very_hard','Muy duro','5/6','☹'],['maximum','Máximo','6/6','☹']];
const extra=document.createElement('style');extra.textContent=`
.pointMap{position:relative;display:block;cursor:crosshair;user-select:none}.pointMap img{display:block;width:100%;height:auto;pointer-events:none}.bodyPoint{position:absolute;width:18px;height:18px;border-radius:999px;background:#e53935;border:3px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.28);transform:translate(-50%,-50%);cursor:pointer;z-index:5}.bodyPoint span{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:9px;font-weight:900;color:#fff}.pointHelp{text-align:center;font-size:12px;color:#627995;margin-top:8px;font-weight:700}.pointSummary{display:flex;flex-direction:column;gap:10px}.pointItem{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px;border:1px solid #dbe7f4;border-radius:12px;background:#fff}.pointItem small{display:block;color:#73879d;margin-top:3px}.pointBadge{display:inline-flex;align-items:center;justify-content:center;min-width:52px;padding:6px 8px;border-radius:10px;background:#eef5ff;color:#1264d8;font-weight:900}.pointActions{display:flex;gap:6px;align-items:center}.pointEdit,.pointRemove{border:0;border-radius:8px;padding:7px 9px;font-weight:800;cursor:pointer}.pointEdit{background:#eef5ff;color:#1264d8}.pointRemove{background:#fff0f0;color:#c82d34}.pointEmpty{padding:18px;border:1px dashed #cbd9e8;border-radius:12px;color:#71869d;text-align:center}.bodyMaps .bodyPanel{min-width:0}.bodyLayout{align-items:start}@media(max-width:780px){.bodyLayout{grid-template-columns:1fr!important}.bodyMaps{grid-template-columns:1fr 1fr!important}.bodyPoint{width:16px;height:16px}}
`;document.head.appendChild(extra);
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
async function call(action,data={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json',...(token?{'authorization':'Bearer '+token}:{})},body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Error de conexión');return j}
function err(el,msg){el.textContent=msg||'';el.style.display=msg?'block':'none'}
function firstName(){return String(state?.user?.displayName||'Jugador').split(' ')[0]}
function initials(){return String(state?.user?.displayName||'A').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function dateLabel(){return state?.today?state.today.split('-').reverse().join('/'):'—'}
function banner(title){return `<div class="playerBanner"><div class="avatar">${esc(initials())}</div><div class="playerText"><small>${esc(title)} · ${esc(dateLabel())}</small><h1>${esc(String(state.user.displayName||'').toUpperCase())}</h1><p>${esc(state.user.team||'Jugador')}</p></div></div><div class="dateBar"><span>FECHA DEL REGISTRO · ${esc(dateLabel())}</span><span>${esc(title)}</span></div>`}
function faces(name,items,value,checkout=false){return `<div class="faceGrid">${items.map((x,i)=>`<button type="button" class="face ${checkout?'checkoutFace':''} ${value===x[0]?'selected':''}" data-choice-name="${name}" data-choice="${x[0]}"><div class="faceIcon c${i+1}">${x[3]}</div><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div>`}
function normalizePoints(raw){return Array.isArray(raw)?raw.filter(p=>Number.isFinite(Number(p.x))&&Number.isFinite(Number(p.y))).map((p,i)=>({id:String(p.id||('pt_'+Date.now()+'_'+i)),view:p.view==='back'?'back':'front',x:Math.max(0,Math.min(100,Number(p.x))),y:Math.max(0,Math.min(100,Number(p.y))),severity:Math.max(1,Math.min(10,Number(p.severity)||5)),comment:String(p.comment||'')})):[]}
function pointStore(type){return type==='checkin'?checkInPoints:checkOutPoints}
function mapHtml(type){const points=pointStore(type);const one=side=>{const sidePts=points.filter(p=>p.view===side);return `<div class="bodyPanel"><h4>${side==='front'?'Vista anterior':'Vista posterior'}</h4><div class="pointMap" data-point-map="${side}" data-kind="${type}"><img src="${ASSET}assets/checkin-body-${side}.jpg" alt="Vista ${side}">${sidePts.map((p,i)=>`<button type="button" class="bodyPoint" data-point-id="${esc(p.id)}" data-kind="${type}" style="left:${p.x}%;top:${p.y}%" title="Dolor ${p.severity}/10"><span>${p.severity}</span></button>`).join('')}</div><div class="pointHelp">Pulsa en el punto exacto del cuerpo</div></div>`};return `<div class="bodyLayout"><div class="bodyMaps">${one('front')}${one('back')}</div><div class="painSummary"><h4>Puntos seleccionados</h4><div id="pointList" class="pointSummary">${pointList(type)}</div></div></div>`}
function pointList(type){const pts=pointStore(type);if(!pts.length)return '<div class="pointEmpty">Pulsa directamente sobre el cuerpo. El punto se añadirá inicialmente con dolor 5/10.</div>';return pts.map((p,i)=>`<div class="pointItem"><div><b>Punto ${i+1} · ${p.view==='front'?'anterior':'posterior'}</b><small>${esc(p.comment||'Sin comentario')}</small></div><div class="pointActions"><span class="pointBadge">${p.severity}/10</span><button type="button" class="pointEdit" data-edit-point="${esc(p.id)}" data-kind="${type}">Editar</button><button type="button" class="pointRemove" data-remove-point="${esc(p.id)}" data-kind="${type}">×</button></div></div>`).join('')}
function bindChoices(){document.querySelectorAll('[data-choice-name]').forEach(b=>b.onclick=()=>{const n=b.dataset.choiceName;document.querySelectorAll(`[data-choice-name="${n}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});bindPoints()}
function bindPoints(){document.querySelectorAll('[data-point-map]').forEach(map=>{map.onclick=e=>{if(e.target.closest('.bodyPoint'))return;const r=map.getBoundingClientRect();const x=((e.clientX-r.left)/r.width)*100,y=((e.clientY-r.top)/r.height)*100;const type=map.dataset.kind,side=map.dataset.pointMap;const pts=pointStore(type);const p={id:'pt_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),view:side,x:Math.round(x*100)/100,y:Math.round(y*100)/100,severity:5,comment:''};pts.push(p);openPoint(type,p.id)}});document.querySelectorAll('[data-point-id]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPoint(b.dataset.kind,b.dataset.pointId)});document.querySelectorAll('[data-edit-point]').forEach(b=>b.onclick=()=>openPoint(b.dataset.kind,b.dataset.editPoint));document.querySelectorAll('[data-remove-point]').forEach(b=>b.onclick=()=>{const pts=pointStore(b.dataset.kind),i=pts.findIndex(p=>p.id===b.dataset.removePoint);if(i>=0)pts.splice(i,1);refreshPoints(b.dataset.kind)})}
function refreshPoints(type){const wrap=document.querySelector(`[data-map-wrap="${type}"]`);if(wrap){wrap.innerHTML=mapHtml(type);bindPoints()}}
function openPoint(type,id){const pts=pointStore(type),p=pts.find(x=>x.id===id);if(!p)return;$('#modalRoot').innerHTML=`<div class="modalBack"><div class="modal"><h3>Punto ${p.view==='front'?'anterior':'posterior'}</h3><p class="muted">Punto exacto marcado en el cuerpo. Ajusta el dolor y añade un comentario si lo necesitas.</p><div class="painValue" id="painValue">${p.severity}/10</div><input id="painSlider" class="slider" type="range" min="1" max="10" step="1" value="${p.severity}"><div class="field"><label>Comentario <span class="muted">(opcional)</span></label><textarea id="painComment" class="textarea" placeholder="Ej. tirantez, golpe, molestia...">${esc(p.comment)}</textarea></div><div class="modalActions"><button id="deletePoint" class="btn danger">Quitar punto</button><button id="cancelModal" class="btn soft">Cancelar</button><button id="savePoint" class="btn primary">Guardar punto</button></div></div></div>`;$('#painSlider').oninput=e=>$('#painValue').textContent=e.target.value+'/10';$('#cancelModal').onclick=()=>{$('#modalRoot').innerHTML='';if(p.comment===''&&p.severity===5&&Date.now()-Number((p.id.match(/^pt_(\d+)/)||[])[1]||0)<10000){} };$('#savePoint').onclick=()=>{p.severity=Number($('#painSlider').value);p.comment=$('#painComment').value.trim();$('#modalRoot').innerHTML='';refreshPoints(type)};$('#deletePoint').onclick=()=>{const i=pts.findIndex(x=>x.id===id);if(i>=0)pts.splice(i,1);$('#modalRoot').innerHTML='';refreshPoints(type)}}
function showChoices(){mode='';$('#backChoice').classList.add('hidden');const ci=!!state.checkIn,co=!!state.checkOut;$('#main').innerHTML=`<div class="heroChoice"><div class="choiceHead"><h1>Hola, ${esc(firstName())}</h1><p>¿Qué quieres completar ahora?</p></div><div class="modeGrid"><button class="modeCard card" data-mode="checkin"><div class="modeIcon">↘</div><h2>Check In</h2><p>Antes del entrenamiento: peso, estado, predisposición, comentario y puntos exactos de dolor.</p><span class="modeStatus ${ci?'done':''}">${ci?'✓ Completado hoy':'Pendiente hoy'}</span></button><button class="modeCard card" data-mode="checkout"><div class="modeIcon">↗</div><h2>Check Out</h2><p>Después del entrenamiento: dureza percibida, comentario y puntos exactos sensibles.</p><span class="modeStatus ${co?'done':''}">${co?'✓ Completado hoy':'Pendiente hoy'}</span></button></div></div>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>b.dataset.mode==='checkin'?showCheckIn():showCheckOut())}
function showCheckIn(){mode='checkin';$('#backChoice').classList.remove('hidden');const e=state.checkIn||{};checkInPoints=normalizePoints(e.pains);$('#main').innerHTML=`<section class="card formShell">${banner('Check In')}<div class="steps"><div class="step"><div class="stepNum">1</div><div><h3>Añade tu peso</h3><p>Es opcional; puedes dejarlo sin contestar.</p><div style="display:flex;align-items:center;gap:10px;max-width:250px"><input id="ciWeight" class="input" type="number" min="20" max="250" step="0.1" placeholder="Ej. 74.5" value="${esc(e.weight||'')}"><b>kg</b></div></div></div><div class="step"><div class="stepNum">2</div><div><h3>¿Cómo te encuentras hoy?</h3><p>Selecciona una respuesta</p>${faces('ciFeeling',FEEL,e.feeling)}</div></div><div class="step"><div class="stepNum">3</div><div><h3>¿Cómo te ves para el entrenamiento?</h3><p>Selecciona una respuesta</p>${faces('ciReady',READY,e.trainingReadiness)}</div></div><div class="step"><div class="stepNum">4</div><div><h3>¿Quieres comentar alguna cosa?</h3><textarea id="ciComment" class="textarea" placeholder="Escríbela aquí...">${esc(e.comment||'')}</textarea></div></div><div class="step"><div class="stepNum">5</div><div><h3>Marca los puntos que tienes más tocados</h3><p>Pulsa exactamente donde notas la molestia. Cada punto es independiente.</p><div data-map-wrap="checkin">${mapHtml('checkin')}</div></div></div></div><div class="submitBar"><button id="saveCheckIn" class="btn primary wide">Guardar Check In</button><div id="formMsg" class="error"></div></div></section>`;bindChoices();$('#saveCheckIn').onclick=saveCheckIn}
function showCheckOut(){mode='checkout';$('#backChoice').classList.remove('hidden');const e=state.checkOut||{};checkOutPoints=normalizePoints(e.pains);$('#main').innerHTML=`<section class="card formShell">${banner('Check Out')}<div class="steps"><div class="step"><div class="stepNum">1</div><div><h3>¿Cómo de duro ha sido el entrenamiento?</h3><p>Selecciona una respuesta</p>${faces('coRpe',RPE,e.rpe,true)}</div></div><div class="step"><div class="stepNum">2</div><div><h3>¿Quieres comentar alguna cosa?</h3><textarea id="coComment" class="textarea" placeholder="Escríbela aquí...">${esc(e.comment||'')}</textarea></div></div><div class="step"><div class="stepNum">3</div><div><h3>Marca los puntos que notas más sensibles</h3><p>Pulsa exactamente donde lo notas. Cada punto conserva su posición exacta.</p><div data-map-wrap="checkout">${mapHtml('checkout')}</div></div></div></div><div class="submitBar"><button id="saveCheckOut" class="btn primary wide">Guardar Check Out</button><div id="formMsg" class="error"></div></div></section>`;bindChoices();$('#saveCheckOut').onclick=saveCheckOut}
function selected(name){return document.querySelector(`[data-choice-name="${name}"].selected`)?.dataset.choice||''}
async function saveCheckIn(){const btn=$('#saveCheckIn'),msg=$('#formMsg');err(msg,'');const feeling=selected('ciFeeling'),trainingReadiness=selected('ciReady');if(!feeling||!trainingReadiness){err(msg,'Selecciona cómo te encuentras y cómo te ves para entrenar');return}btn.disabled=true;btn.textContent='Guardando...';try{const r=await call('submit_checkin',{payload:{weight:$('#ciWeight').value,feeling,trainingReadiness,comment:$('#ciComment').value,pains:checkInPoints}});state.checkIn=r.entry;btn.textContent='✓ Check In guardado';setTimeout(showChoices,700)}catch(e){err(msg,e.message);btn.disabled=false;btn.textContent='Guardar Check In'}}
async function saveCheckOut(){const btn=$('#saveCheckOut'),msg=$('#formMsg');err(msg,'');const rpe=selected('coRpe');if(!rpe){err(msg,'Selecciona cómo de duro ha sido el entrenamiento');return}btn.disabled=true;btn.textContent='Guardando...';try{const r=await call('submit_checkout',{payload:{rpe,comment:$('#coComment').value,pains:checkOutPoints}});state.checkOut=r.entry;btn.textContent='✓ Check Out guardado';setTimeout(showChoices,700)}catch(e){err(msg,e.message);btn.disabled=false;btn.textContent='Guardar Check Out'}}
async function boot(){if(!token)return;try{state=await call('me');$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');showChoices()}catch{localStorage.removeItem('arlabPlayerToken');token=''}}
$('#loginBtn').onclick=async()=>{const b=$('#loginBtn'),el=$('#loginErr');err(el,'');b.disabled=true;b.textContent='Entrando...';try{const r=await call('login',{username:$('#user').value,password:$('#pass').value});token=r.token;localStorage.setItem('arlabPlayerToken',token);state=await call('me');$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');showChoices()}catch(e){err(el,e.message);b.disabled=false;b.textContent='Entrar'}};
$('#pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#logoutBtn').onclick=async()=>{try{await call('logout')}catch{}localStorage.removeItem('arlabPlayerToken');location.reload()};
$('#backChoice').onclick=showChoices;
boot();
})();